version: "3"

services:
  ### LOCAL APPLICATION
  cleaning-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_IMAGE: ${BUILD_IMAGE:-maven:3.8.1-openjdk-11}
        RUNTIME_IMAGE: ${RUNTIME_IMAGE:-openjdk:11-jre-slim}
    command: java -Xmx512m -Xms512m -Dspring.profiles.active=local -jar /app/application.jar
    restart: always
    working_dir: /app/
    healthcheck:
      test: ["CMD", "nc", "-vzw", "2", "127.0.0.1", "8080"]
      interval: 10s
      timeout: 9s
      retries: 3
    ports:
      - 127.0.0.1:${APP_PORT:-80}:8080
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/cleaning_db?currentSchema=cleaning_db
    depends_on:
      - postgres

  ### LOCAL POSTGRES
  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cleaning_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres: